version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/La_Paz
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jQuery
    versions:
    - 3.6.0
  - dependency-name: Microsoft.jQuery.Unobtrusive.Validation
    versions:
    - 3.2.12
  - dependency-name: jQuery.Validation
    versions:
    - 1.19.3
  - dependency-name: bootstrap
    versions:
    - 4.6.0
